### ISSUE TITLE
小爱控制的时候报错

### ISSUE THREAD

**Issue by yaowans** [toohandsome/xiaomi2meidi#1]
大佬，按照您的教程设置好后，小爱语音执行的时候报错了，在点灯app上看到设备是离线的，下面的报错的日志，帮忙看下
![1](https://user-images.githubusercontent.com/21300948/190404416-673cbed8-dda7-46e9-ae7c-6e3a9c93addc.png)
![2](https://user-images.githubusercontent.com/21300948/190404422-083f8c03-8284-4f37-92d7-9816093054d2.png)

**Comment by toohandsome** [comment]
好的，看起来是fastjson 序列化的错，我修改一下

**Comment by toohandsome** [comment]
请下载 0.0.3 重试
